TDC/TDC/Controllers/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TDC.Models;
using TDC.Tools;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;


namespace TDC.Controllers
{
    public class ExpensesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Expenses
        public ActionResult Index()
        {
            return View(db.Expenses.ToList());
        }

        // GET: Expenses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            return View(expense);
        }

        // GET: Expenses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Expenses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,product,cost,UserID")] Expense expense)
        {
            if (ModelState.IsValid && expense.cost != null && expense.product != null)
            {
                var user = UserActions.getUser(User.Identity.GetUserId());
                expense.cost = expense.cost * -1;
                expense.UserID = User.Identity.GetUserId();
                expense.Date = DateTime.Now.AddHours(user.TimeZoneOffset);
                db.Expenses.Add(expense);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("Index", "Home"); 
        }

        // GET: Expenses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            return View(expense);
        }

        // POST: Expenses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,product,cost,UserID")] Expense expense)
        {
            if (ModelState.IsValid)
            {
                db.Entry(expense).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(expense);
        }

        // GET: Expenses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            return View(expense);
        }

        // POST: Expenses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Expense expense = db.Expenses.Find(id);
            db.Expenses.Remove(expense);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TDC/TDC/Controllers/HomeController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TDC.Models;
using TDC.Tools;

namespace TDC.Controllers
{
    public class HomeController : Controller
    {
        //This shows how to get currently signed in user.

        private ApplicationDbContext db = new ApplicationDbContext();
        

        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated == true)
            {

                var user = UserActions.getUser(User.Identity.GetUserId());
               // var shock = ShockCalc.doIndShock(user.Id);
                ShockCalc.eventChecker(user);
                ViewBag.message = UserActions.messageParser(user);
                
                

                


                return View(user);
            }
            else return RedirectToAction("Splash", "Home");
            
          
        }

        public ActionResult RemitanceForm()
        {


            return View();

        }
        [HttpPost]
        public ActionResult RemitanceForm(string recipiant, decimal amt)
        {
            var user = UserActions.getUser(User.Identity.GetUserId());
            var recpiantObject = db.Users.Where(x => x.Email == recipiant).ToList();
            if (amt < user.getBalance() && recpiantObject.Count > 0 && amt > 0)
            {
                UserActions.sendRemit(user, recpiantObject.First() , amt);


            }




            return RedirectToAction("Index");
        }

        public ActionResult About()
        {
            
            ViewBag.Message = "Your application description page.";
            //use this to get current user
            var userTest = UserActions.getUser(User.Identity.GetUserId());
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Splash()
        {
            return View();
        }

        public ActionResult Stats()
        {
            ViewBag.teamMoney =  TeamStats.getTeamMoney().OrderByDescending(x => x.amt);
            ViewBag.teamTotal = TeamStats.getPopItem().OrderByDescending(x => x.amt);
            ViewBag.numOnTeams = TeamStats.getTotalTeam().OrderByDescending(x => x.amt);
            //ViewBag.RichPlayer = db.Users.Where(x => x.Expense.Count > 0).Select(x => new {Email = x.Email , TotalSum = x.Income.Sum(y => y.Amount) - x.Expense.Sum(z => z.cost) }).OrderByDescending(d => d.TotalSum).Take(10).ToList();
            var people = db.Users.Where(x => x.Expense.Count > 0).ToList();
            people = people.OrderByDescending(x => x.getBalance()).Take(10).ToList();
            var ppeople= db.Users.Where(x => x.Expense.Count > 0).ToList();
            ViewBag.poor = ppeople.OrderBy(x => x.getBalance()).Take(10).ToList();
            return View(people);
        }

        public ActionResult ReflectionView() {
            var user = UserActions.getUser(User.Identity.GetUserId());

            return View(user.Reflection.ToList());
        }
        public ActionResult CreateReflection()
        {
            
            return View();
        }

        // POST: Expenses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateReflection([Bind(Include = "ID, Memo")]  Reflection reflection)
        {
            if (ModelState.IsValid)
            {


                var user = UserActions.getUser(User.Identity.GetUserId());
                reflection.UserId = user.Id;
                reflection.Date = DateTime.Now;
                db.Reflections.Add(reflection);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View("CreateReflection");
        }



    }
}

TDC/TDC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TDC/TDC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TDC/TDC/Views/Home/CreateReflection.cshtml
@model TDC.Models.Reflection

@{
    ViewBag.Title = "Reflection";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-xs-8 col-xs-push-2">
        <div class="panel box-shadows-rock" style="padding: 10px 10px 10px 10px">
            <h2 class="text-center" style="color:#A62900; font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">@ViewBag.Title</h2>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel box-shadows-rock" style="padding: 10px 10px 10px 10px">
            <div class="row">
                <div class="col-lg-12">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">

                            <div class="form-group text-center">
                                <div class="row">
                                    <div class="col-xs-12">
                                        @Html.LabelFor(model => model.Memo, htmlAttributes: new { @class = "control-label" }) - 140 char limit
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-xs-10 col-xs-offset-1">
                                        @Html.EditorFor(model => model.Memo, new { htmlAttributes = new { @class = "full-width" } })
                                        @Html.ValidationMessageFor(model => model.Memo, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="row">
                                    <div class="col-xs-10 col-xs-offset-1">
                                        <input type="submit" value="Submit" class="btn btn-default full-width" style="margin-left: auto; margin-right: auto;" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>

</div>

TDC/TDC/Views/Home/Index.cshtml
@using TDC.Models
@using TDC.Tools

@model TDC.Models.User
@{

    
    ViewBag.Title = "Home Page";
}


<div class="container">
    <!-- Add Expense Modal -->
    
    <div class="row">
        <div class="col-xs-8 col-xs-push-2">
            <div class="panel box-shadows-rock" style="padding: 10px 10px 10px 10px">
                <h2 class="text-center" style="color:#A62900; font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">You @(Model.getBalance() < 0 ? "owe" : "have") $@Math.Abs(Model.getBalance()) </h2>
            </div>
        </div>
    </div>




    <div class="row">
        <div >

            <div class="panel panel-default box-shadows-rock">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-10 col-xs-offset-1">
                            <a href="#" data-target="#modalExpense" data-toggle="modal" class="btn btn-default btn-lg btn-block btn-danger" style="margin:10px,5px,10px,5px"><span class="glyphicon glyphicon-plus"></span> Expense</a>
                        </div>
                    </div>
                    <hr />
                    <div class="row">
                        <div class="col-xs-10 col-xs-offset-1">
                            <a href="#" data-target="#modalLog" data-toggle="modal" class="btn btn-default btn-lg btn-block btn-info"><span class="glyphicon glyphicon-th-list"></span>  Log</a>
                        </div>
                    </div>
                    <hr/>
                    <div class="row">
                        <div class="col-xs-10 col-xs-offset-1">
                            <a href="#" data-target="#modalSendRemit" data-toggle="modal" class="btn btn-default btn-lg btn-block btn-success"><span class="glyphicon glyphicon-gift"></span> Send Money</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">

        <div class="col-xs-12 col-sm-8 col-sm-push-2 col-lg-6 col-lg-push-3 text-center">

            <a class="twitter-timeline" href="https://twitter.com/tdchallenge" data-widget-id="544296033954840576">Tweets by @@tdchallenge</a>
            <script>!function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https'; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = p + "://platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs); } }(document, "script", "twitter-wjs");</script>

        </div>
    </div>
    </div>
    



<div class="modal" id="modalExpense" data-backdrop="false">
    <div class="modal-dialog">
        <div class="modal-content" style="background-color: #DEDEDE">
            @using (Html.BeginForm("create", "Expenses"))
            {

                @*<div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Add Expense</h4>
                </div>*@
                <div class="modal-body">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    @Html.Partial("~/Views/Expenses/Create.cshtml", new TDC.Models.Expense())

                </div>
                @*<div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Add</button>
                </div>*@
            }
        </div>
    </div>
</div>
<div class="modal" id="modalSendRemit" data-backdrop="false">
    <div class="modal-dialog">
        <div class="modal-content" style="background-color: #DEDEDE">
            @using (Html.BeginForm("RemitanceForm", "Home"))
            {

                @*<div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title">Add Expense</h4>
                    </div>*@
                <div class="modal-body">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    @Html.Partial("~/Views/Home/RemitanceForm.cshtml")

                </div>
                @*<div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Add</button>
                    </div>*@
            }
        </div>
    </div>
</div>

<!-- View Log Modal -->
<div class="modal" id="modalLog" data-backdrop="false">
    <div class="modal-dialog">
        <div class="modal-content" style="background-color: #DEDEDE">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 class="text-center" style="color:#A62900; font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">History of Events</h3>
                <hr />

            </div>
            <div class="modal-body">
                <table class="table table-bordered table-responsive table-striped box-shadows-rock" style="background-color:#FFFFFF">
                    <thead>
                        <tr>
                            <th width="100px">
                                Date
                            </th>
                            <th width="100px">
                                Type
                            </th>
                            <th width="100px">
                                Amt
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @{int i = 1;}
                        @foreach (var x in UserActions.getLog(Model.Id))
                        {

                            string classType = "";
                            if (String.Equals(x.getType(), "Income")) { classType = "success"; }
                            else if (String.Equals(x.getType(), "Expense")) { classType = "danger"; }
                            else if (String.Equals(x.getType(), "Expense")) { classType = "danger"; }


                            <tr class=@classType>
                                <td>
                                    @x.getDate().ToString("g")
                                </td>
                                <td>
                                    @x.getType()
                                </td>
                                <td>
                                    @x.getAmt()
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
            @*<div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>

            </div>*@
        </div>
    </div>
    @*Will be used to alert user to shocks.*@


  <script>
      @{string message = ViewBag.message;}
      @{string thing = "Cats";}
      var thing = "@HttpUtility.JavaScriptStringEncode(message)";
     
      
  </script> 
    


</div>
<body onload="eventAlert(thing)"></body>

<script type="text/javascript" src="~/Tools/ShockControl.js"></script>

TDC/TDC/Views/Home/ReflectionView.cshtml
@model IEnumerable<TDC.Models.Reflection>

@{
    ViewBag.Title = "ReflectionView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-xs-8 col-xs-push-2">
        <div class="panel box-shadows-rock" style="padding: 10px 10px 10px 10px">
            <h2 class="text-center" style="color:#A62900; font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">Reflection</h2>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-lg-12">
        <div class="panel box-shadows-rock" style="padding: 10px 10px 10px 10px">
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1">
                    <p>
                        @Html.ActionLink("Create New Reflection", "CreateReflection", "Home", null, new { @class = "btn btn-default full-width" })
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <table class="table table-bordered table-responsive table-striped" style="background-color:#FFFFFF">
                        <tr>

                            <th>
                                @Html.DisplayNameFor(model => model.Date)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Memo)
                            </th>

                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>

                                <td>
                                    @Html.DisplayFor(modelItem => item.Date)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Memo)
                                </td>
                                @*<td>
                            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
                            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
                            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
                        </td>*@
                            </tr>
                        }

                    </table>

                </div>
            </div>
        </div>
    </div>
</div>

TDC/TDC/Views/Home/RemitanceForm.cshtml
@model dynamic

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3 class="text-center red-text" style="font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">Expense</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group text-center">
            <div class="row">
                <div class="col-xs-10 col-xs-push-1">
                    <label class="control-label expense-modal red-text" for="recipiant"> Enter Recipiant Email</label>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6 col-xs-offset-3">
                    <input type="text" id="recipiant" name="recipiant" class="form-control text-center" />  
                </div>
            </div>

        </div>

        <div class="form-group text-center">
            <div class="row">
                <div class="col-xs-10 col-xs-push-1">
                    <label class="control-label expense-modal red-text" for="recipiant">Enter amount</label>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6 col-xs-offset-3">
                    <input type="text" id="amt" name="amt" class="form-control text-center" />   
                </div>
            </div>
        </div>


        <div class="modal-footer">
            <div class="form-group text-center">
                <div class="row">
                    <div class="col-xs-8 col-xs-offset-2">
                        <input type="submit" value="Add" class="btn btn-danger" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    $('#myFormSubmit').click(function(e){
    e.preventDefault();
    alert($('#myField').val());
    });
}

TDC/TDC/Views/Home/Splash.cshtml
@using TDC.Models
@model LoginViewModel
@{
   
    ViewBag.Title = "Splash";
}

@*<section id="main-slider" class="no-margin">
    <div class="carousel slide">
        <ol class="carousel-indicators">
            <li data-target="#main-slider" data-slide-to="0" class="active"></li>
            <li data-target="#main-slider" data-slide-to="1"></li>
            <li data-target="#main-slider" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">

            <div class="item active" style="background-image: url(http://twodollarchallenge.org/wp-content/uploads/2014/10/65625_10151579765780821_182816571_n-e1415104747334.jpg)">
                <div class="container">
                    <div class="row slide-margin">
                        <div class="col-sm-6">
                            <div class="carousel-content">
                                <h1 class="animation animated-item-1">Lorem ipsum dolor sit amet consectetur adipisicing elit</h1>
                                <h2 class="animation animated-item-2">Accusantium doloremque laudantium totam rem aperiam, eaque ipsa...</h2>
                                <a class="btn-slide animation animated-item-3" href="#">Register</a>
                                <a class="btn-slide animation animated-item-3" href="#">Log In</a>
                            </div>
                        </div>

                        <div class="col-sm-6 hidden-xs animation animated-item-4">
                            <div class="slider-img">
                                <img src="images/slider/img1.png" class="img-responsive">
                            </div>
                        </div>

                    </div>
                </div>
            </div><!--/.item-->

            <div class="item" style="background-image: url(images/slider/bg2.jpg)">
                <div class="container">
                    <div class="row slide-margin">
                        <div class="col-sm-6">
                            <div class="carousel-content">
                                <h1 class="animation animated-item-1">Lorem ipsum dolor sit amet consectetur adipisicing elit</h1>
                                <h2 class="animation animated-item-2">Accusantium doloremque laudantium totam rem aperiam, eaque ipsa...</h2>
                                <a class="btn-slide animation animated-item-3" href="#">Read More</a>
                            </div>
                        </div>

                        <div class="col-sm-6 hidden-xs animation animated-item-4">
                            <div class="slider-img">
                                <img src="images/slider/img2.png" class="img-responsive">
                            </div>
                        </div>

                    </div>
                </div>
            </div><!--/.item-->

            <div class="item" style="background-image: url(images/slider/bg3.jpg)">
                <div class="container">
                    <div class="row slide-margin">
                        <div class="col-sm-6">
                            <div class="carousel-content">
                                <h1 class="animation animated-item-1">Lorem ipsum dolor sit amet consectetur adipisicing elit</h1>
                                <h2 class="animation animated-item-2">Accusantium doloremque laudantium totam rem aperiam, eaque ipsa...</h2>
                                <a class="btn-slide animation animated-item-3" href="#">Read More</a>
                            </div>
                        </div>
                        <div class="col-sm-6 hidden-xs animation animated-item-4">
                            <div class="slider-img">
                                <img src="images/slider/img3.png" class="img-responsive">
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->
        </div><!--/.carousel-inner-->
    </div><!--/.carousel-->

</section><!--/#main-slider-->*@
@*<body>

<div id="main-slider" class="carousel slide">
    <ol class="carousel-indicators">
        <li data-target = "#main-slider" data-slide-to="0" class="active"></li>
        <li data-target = "#main-slider" data-slide-to="1"></li>
        <li data-target = "#main-slider" data-slide-to="2"></li>
    </ol>
</div>
<div class="carousel-inner">
    <div class="item active" >
        
    </div>
    <div class="item">
        <img src="~/images/slider/bg2.jpg" class="img-responsive" />
    </div>
    <div class="item">
        <img src="~/images/slider/bg3.jpg"  class="img-responsive" />
    </div>
</div>
    <a class="carousel-control" href="#main-slider" data-slide = "prev">
        <span class="icon-prev"></span>
    </a>
</body>*@

 

@* I tried again <style>
    #pics {
        height: 300px;

    }
</style>
<div id="myCarousel" class="carousel slide" style="max-height: 300px !important;">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <!-- Carousel items -->
    <div class="carousel-inner">
        <div id="pics" class="active item"><img src="~/images/slider/bg1.jpg" class="img-responsive" /></div>
        <div id="pics" class="item"><img src="~/images/slider/bg2.jpg" class="img-responsive" /></div>
        <div id="pics" class="item"><img src="~/images/slider/bg3.jpg" class="img-responsive" /></div>
    </div>
    <!-- Carousel nav -->
    <a class=" left carousel-control " href="#myCarousel" role="button" data-slide="prev"> <span class=" glyphicon-chevron-left"></span></a>
    <a class="right carousel-control " href="#myCarousel" role="button" data-slide="next"><span class="glyphicon-chevron-right"></span></a>
</div>*@


<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <h1><center>Welcome! Please make an account!</center></h1>
        <center>
        <p><a class="btn btn-primary btn-lg" href="~/Account/Register" role="button">Register &raquo;</a>
        <a class="btn btn-primary btn-lg" href="~/Account/Login" role="button">Login&raquo;</a></p>
            </center>
    </div>
</div>

@*<div class="container">
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
    </div>

    <hr>

>
</div> <!-- /container -->*@